package sdl

/*
#include <SDL.h>
*/
import "C"

type AudioStatus int

const (
	ENABLE = C.SDL_ENABLE
	IGNORE = C.SDL_IGNORE
	QUERY  = C.SDL_QUERY
)

const (
	INIT_VIDEO      = C.SDL_INIT_VIDEO
	INIT_AUDIO      = C.SDL_INIT_AUDIO
	INIT_TIMER      = C.SDL_INIT_TIMER
	INIT_JOYSTICK   = C.SDL_INIT_JOYSTICK
	INIT_EVERYTHING = C.SDL_INIT_EVERYTHING
)

const (
	AUDIO_U8     AudioFormat = C.AUDIO_U8
	AUDIO_S8                 = C.AUDIO_S8
	AUDIO_U16LSB             = C.AUDIO_U16LSB
	AUDIO_S16LSB             = C.AUDIO_S16LSB
	AUDIO_U16MSB             = C.AUDIO_U16MSB
	AUDIO_S16MSB             = C.AUDIO_S16MSB
	AUDIO_U16                = C.AUDIO_U16
	AUDIO_S16                = C.AUDIO_S16
	AUDIO_S32LSB             = C.AUDIO_S32LSB
	AUDIO_S32MSB             = C.AUDIO_S32MSB
	AUDIO_S32                = C.AUDIO_S32
	AUDIO_F32LSB             = C.AUDIO_F32LSB
	AUDIO_F32MSB             = C.AUDIO_F32MSB
	AUDIO_F32                = C.AUDIO_F32
)

const (
	AUDIO_ALLOW_FREQUENCY_CHANGE = C.SDL_AUDIO_ALLOW_FREQUENCY_CHANGE
	AUDIO_ALLOW_FORMAT_CHANGE    = C.SDL_AUDIO_ALLOW_FORMAT_CHANGE
	AUDIO_ALLOW_CHANNELS_CHANGE  = C.SDL_AUDIO_ALLOW_CHANNELS_CHANGE
	AUDIO_ALLOW_ANY_CHANGE       = C.SDL_AUDIO_ALLOW_ANY_CHANGE
)

const (
	AUDIO_STOPPED AudioStatus = C.SDL_AUDIO_STOPPED
	AUDIO_PAUSED  AudioStatus = C.SDL_AUDIO_PAUSED
	AUDIO_PLAYING AudioStatus = C.SDL_AUDIO_PLAYING
)

const (
	WINDOW_FULLSCREEN    = C.SDL_WINDOW_FULLSCREEN
	WINDOW_OPENGL        = C.SDL_WINDOW_OPENGL
	WINDOW_SHOWN         = C.SDL_WINDOW_SHOWN
	WINDOW_HIDDEN        = C.SDL_WINDOW_HIDDEN
	WINDOW_BORDERLESS    = C.SDL_WINDOW_BORDERLESS
	WINDOW_RESIZABLE     = C.SDL_WINDOW_RESIZABLE
	WINDOW_MINIMIZED     = C.SDL_WINDOW_MINIMIZED
	WINDOW_MAXIMIZED     = C.SDL_WINDOW_MAXIMIZED
	WINDOW_INPUT_GRABBED = C.SDL_WINDOW_INPUT_GRABBED
	WINDOW_INPUT_FOCUS   = C.SDL_WINDOW_INPUT_FOCUS
	WINDOW_MOUSE_FOCUS   = C.SDL_WINDOW_MOUSE_FOCUS
	WINDOW_FOREIGN       = C.SDL_WINDOW_FOREIGN
)

const (
	RENDERER_SOFTWARE      = C.SDL_RENDERER_SOFTWARE
	RENDERER_ACCELERATED   = C.SDL_RENDERER_ACCELERATED
	RENDERER_PRESENTVSYNC  = C.SDL_RENDERER_PRESENTVSYNC
	RENDERER_TARGETTEXTURE = C.SDL_RENDERER_TARGETTEXTURE
)

const (
	TEXTUREACCESS_STATIC    = C.SDL_TEXTUREACCESS_STATIC
	TEXTUREACCESS_STREAMING = C.SDL_TEXTUREACCESS_STREAMING
	TEXTUREACCESS_TARGET    = C.SDL_TEXTUREACCESS_TARGET
)

const (
	TEXTUREMODULATE_NONE  = C.SDL_TEXTUREMODULATE_NONE
	TEXTUREMODULATE_COLOR = C.SDL_TEXTUREMODULATE_COLOR
	TEXTUREMODULATE_ALPHA = C.SDL_TEXTUREMODULATE_ALPHA
)

const (
	BLENDMODE_NONE  = C.SDL_BLENDMODE_NONE
	BLENDMODE_BLEND = C.SDL_BLENDMODE_BLEND
	BLENDMODE_ADD   = C.SDL_BLENDMODE_ADD
	BLENDMODE_MOD   = C.SDL_BLENDMODE_MOD
)

const (
	FLIP_NONE       Flip = C.SDL_FLIP_NONE
	FLIP_HORIZONTAL      = C.SDL_FLIP_HORIZONTAL
	FLIP_VERTICAL        = C.SDL_FLIP_VERTICAL
)

const (
	PIXELFORMAT_UNKNOWN   = C.SDL_PIXELFORMAT_UNKNOWN
	PIXELFORMAT_INDEX1LSB = C.SDL_PIXELFORMAT_INDEX1LSB
	PIXELFORMAT_RGBA8888  = C.SDL_PIXELFORMAT_RGBA8888
	PIXELFORMAT_ARGB8888  = C.SDL_PIXELFORMAT_ARGB8888
)
